#!/usr/bin/env python3
"""Regenerate `benches/data/lichess_games.txt` from the Kaggle Lichess dataset.

    curl -L -o chess.zip https://www.kaggle.com/api/v1/datasets/download/datasnaek/chess
    python3 -c "import zipfile; zipfile.ZipFile('chess.zip').extractall()"
    uv run --with chess scripts/lichess_games.py games.csv > benches/data/lichess_games.txt

Source: "Chess Game Dataset (Lichess)" by Mitchell J, https://www.kaggle.com/datasets/datasnaek/chess
(CC0: Public Domain), about 20,000 Lichess games with their moves in SAN.

A fixed-seed sample of games is converted from SAN to UCI with python-chess, so the
benchmarks only need the engine's own UCI parser. The benchmarks replay every game with
`Game::play`, which rejects illegal moves, so the engine checks the conversion too.
"""
import argparse
import csv
import random

import chess

SEED = 2017
GAMES = 100
MIN_PLIES = 10


def to_uci(san_moves):
    board = chess.Board()
    uci = []
    for san in san_moves.split():
        move = board.parse_san(san)
        uci.append(move.uci())
        board.push(move)
    return uci, board


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv", help="games.csv from the Kaggle dataset")
    ap.add_argument("--games", type=int, default=GAMES)
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args()

    with open(args.csv, newline="") as f:
        rows = list(csv.DictReader(f))
    # The dataset lists some games twice.
    rows = list({r["id"]: r for r in rows}.values())
    rows = [r for r in rows if int(r["turns"]) >= MIN_PLIES]
    sample = random.Random(args.seed).sample(rows, args.games)

    print("# Lichess games sampled from https://www.kaggle.com/datasets/datasnaek/chess (CC0: Public Domain).")
    print(f"# Generated by scripts/lichess_games.py (seed {args.seed}, {args.games} games of at least {MIN_PLIES} plies).")
    print("# Format: <lichess id> <victory status> <winner> <moves in UCI>...")
    for r in sample:
        uci, board = to_uci(r["moves"])
        assert len(uci) == int(r["turns"]), r["id"]
        assert (r["victory_status"] == "mate") == board.is_checkmate(), r["id"]
        print(r["id"], r["victory_status"], r["winner"], " ".join(uci))


if __name__ == "__main__":
    main()
